FROM python:2.7
ADD requirements.txt /app/requirements.txt
WORKDIR /app/
RUN pip install -r requirements.txt
ADD ./celery_example/ /app/
ENTRYPOINT celery -A celery_example worker --concurrency=20 --loglevel=info
